### ISSUE TITLE
Handlebars error: Could not find property 'file-picker'

### ISSUE THREAD

**Issue by jackmatt2** [funkensturm/ember-cli-file-picker#1]
I am getting the following error on ember-cli@0.1.4 any ideas why?

```
Uncaught Error: <dummy@view:default::ember491> Handlebars error: Could not find property 'file-picker' on object <dummy@controller:showcase/file-uploader::ember568>.
```

package.json contains: "ember-cli-uploader": "^0.3.0",
bower.json contains: "ember-uploader": "~0.3.0"

**Comment by jackmatt2** [comment]
Well 
```
npm install --save-dev ember-cli-file-picker
```
instead of 
```
npm install --save-dev ember-cli-uploader
```
seems to work, I think the docs are wrong

**Comment by fsmanuel** [comment]
@jackmatt2 [ember-cli-uploader](https://github.com/benefitcloud/ember-cli-uploader) is a different project.

**Comment by jackmatt2** [comment]
But in the instructions in README.md is says
```
npm install --save-dev ember-cli-uploader
```

**Comment by fsmanuel** [comment]
@jackmatt2 You are totally right. Thanks for the hint. I updated the readme.
