### ISSUE TITLE
Trigger in iOS7

### ISSUE THREAD

**Issue by Chrissvo** [funkensturm/ember-cli-file-picker#12]
Did a few tests on [BrowserStack](https://www.browserstack.com), works great with iOS8, but it looks like file-picker is not triggered in iOS7.

Using:
```hbs
{{#file-picker fileLoaded="fileLoaded"}}
    Drag here or click to upload a file
{{/file-picker}}
```

**Comment by harianus** [comment]
Having the same problem at my machine!

**Comment by fsmanuel** [comment]
@Chrissvo Do you have any insides what's going wrong? On a quick research i found [this](http://stackoverflow.com/questions/793014/jquery-trigger-file-input), [this](http://stackoverflow.com/questions/19838846/mobile-safari-file-upload-popup-position) and [this](http://stackoverflow.com/questions/12805940/trigger-file-input-dialog-programatically-on-ios-6)

**Comment by Chrissvo** [comment]
@fsmanuel, I did some more testing and found out that file-picker is working on iOS 7 if I use a tablet. I'm rendering a different template for phones, so the issue must be somewhere in my own code. Closing issue and thanks for the quick reply!

**Comment by fsmanuel** [comment]
@Chrissvo no problem.
