### ISSUE TITLE
Repeat file upload fails on webkit

### ISSUE THREAD

**Issue by nicford-gojimo** [funkensturm/ember-cli-file-picker#130]
Hi - we're seeing a situation where repeat upload via click and dialog fails on webkit browsers i.e Chrome and Safari (Firefox is fine):
1. click on the dropzone to open the system file dialog
2. choose a file (we're using PNG and JPG); double-click or click OK/Open
3. watch the file upload
4. click on the dropzone to open the system file dialog again
5. choose the same file; double-click or click OK/Open
6. nothing happens

Note that dragging images from Explorer/Finder onto the dropzone works fine even if the same file is used.

Is this a known problem? I can't find mention of it via Google.

Cheers

Nic Ford
Gojimo

**Comment by fsmanuel** [comment]
@nicford-gojimo thanks for reporting. The problem is that webkit doesn't fire the `change` event if the filename is the same. Somehow we should reset the `this.$('.file-picker__input')` to `null` in `handleFiles`. 

You can try to overwrite `handleFiles` like this:

```js
handleFiles: function(files) {
  this._super(...arguments);

  this.$('.file-picker__input').val(null);
}
```

If it works I'm happy to accept a PR.

**Comment by nicford-gojimo** [comment]
Thanks - I'll have a play and see if I can fix it.

**Comment by nicford-gojimo** [comment]
Yes, that absolutely fixes it. I'll submit a PR.

-- 

*Nic Ford*

Head of Technology, Gojimo

Gojimo is available on iOS <http://m.onelink.me/44374fef>, Android
<http://m.onelink.me/feee4922> (beta) and web <http://app.gojimo.co/> (beta)

EducationApps Ltd is a registered company in England, No. 07556427

Gojimo, c/o Edspace, Block D Room 203, Hackney Community College, London N1
6HQ

**Comment by fsmanuel** [comment]
I'll review it tomorrow and check why the tests are failing.

**Comment by nicford-gojimo** [comment]
Thanks - tests missing from final commit, but as far as I got was in an
earlier commit that you should be able to see.

-- 

*Nic Ford*

Head of Technology, Gojimo

Gojimo is available on iOS <http://m.onelink.me/44374fef>, Android
<http://m.onelink.me/feee4922> (beta) and web <http://app.gojimo.co/> (beta)

EducationApps Ltd is a registered company in England, No. 07556427

Gojimo, c/o Edspace, Block D Room 203, Hackney Community College, London N1
6HQ

**Comment by fsmanuel** [comment]
I'll release a new version in some hours.

**Comment by fsmanuel** [comment]
@nicford-gojimo released `0.0.10` Thanks for the PR!

**Comment by xamoom-pali** [comment]
I'm facing same problem, however, my hideFileInput flag is true by default and thus 
the `if` branch never gets executed. What is the reason to check for `hideFileInput`?

**Comment by georgholzer** [comment]
Good Job! Thanks a lot!
