### ISSUE TITLE
Option to not hide input

### ISSUE THREAD

**Issue by aequitas** [funkensturm/ember-cli-file-picker#14]
The native file input field is well known to users, I would like to keep it visible instead of building my own input representation. Could you add an option to not hide the input field?

**Comment by fsmanuel** [comment]
@aequitas sounds good to me. Do you have time to open a PR? Should be easy. The option should be `hideFileInput` and defaults to `true`. In the `didInsertElement` hook you wrap the `this.hideInput()` with `if (this.get('hideFileInput'))`. If you don't have time I'll do it on Monday.

**Comment by aequitas** [comment]
Hi @fsmanuel, I hacked something similar up to make it work in our local environment last week. I can make that into a pull request and push it today.

**Comment by fsmanuel** [comment]
@aequitas i just pushed 0.0.8 with the new option. check it out and report problems if you encounter.

**Comment by aequitas** [comment]
@fsmanuel works as expected, thx!
