### ISSUE TITLE
CSP unsafe-inline

### ISSUE THREAD

**Issue by jelhan** [funkensturm/ember-cli-file-picker#17]
Ember-cli-file-picker uses inline style for progress bar. https://github.com/funkensturm/ember-cli-file-picker/blob/master/app/templates/components/file-picker.hbs#L15 That's a problem concerning CSP. We have to a) allow `unsafe-inline` for `style-src` or b) add all 101 possible hashes (width: 0% ... width: 100%) to `style-src` which blows up HTTP Header.

`progress` HTML tag (https://developer.mozilla.org/de/docs/Web/HTML/Element/progress) seems to be the way to go but it isn't supported by IE <= 9: http://caniuse.com/#feat=progress

**Comment by fsmanuel** [comment]
@jelhan right now i don't want to shut IE 9 out. What you can do is copy the template in your app and overwrite it.

**Comment by fsmanuel** [comment]
@jelhan did you solve the problem? Can I close the issue?

**Comment by jelhan** [comment]
Overwriting template is fine for me. But it doesn't seems to be a clean solution for future. Not tested yet, but wouldn't it possible to use [Modernizr test for progress support](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/elem/progress-meter.js) and only fallback to inline styles if it's not supported by current browser? The browsers which doesn't support progress element also [doesn't support CSP](http://caniuse.com/#feat=contentsecuritypolicy).

**Comment by fsmanuel** [comment]
@jelhan I don't want to pull in modernizr but we can copy the checks and do the fallback. I'm happy to accept a PR.
