### ISSUE TITLE
CarrierWave usage & strong params

### ISSUE THREAD

**Issue by febero** [funkensturm/ember-cli-file-picker#2]
I'm trying to implement the CarrierWave example shown in the Readme but I'm gettting 500 error. 
```
    `NoMethodError (undefined method []' for nil:NilClass):`
    `app/controllers/posts_controller.rb:3:in create`
```
Top part of PostsController:
```ruby
class PostsController < ApplicationController
  def create
    post_params[:post][:image] = convert_to_upload(post_params[:post][:image])
    @post = Post.create(post_params)
  end
```
It seems related to strong params and I assume they aren't parsed correctly, but maybe I'm missing the point. I thought setting strong params like this would have worked, but it didn't !

```ruby
  private
    def post_params
      params.require(:post).permit(image: [:date, :filename, :type, :size])
    end
```
Before trying to implement strong parameters, I was getting another 500 error : 
```
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  app/controllers/posts_controller.rb:4:in `create'
```
Any input will be much appreciated!

**Comment by fsmanuel** [comment]
Hey @febero can you try to setup your post_params like that:
```ruby
private
    def post_params
      params.require(:post).permit(:image)
    end
```

**Comment by fsmanuel** [comment]
actually i don't use the strong params for convert_to_upload but for the create:
```ruby
def create
      params[:post][:image] = convert_to_upload(params[:post][:image])
      params[:post].delete(:image) unless params[:post][:image]

      Post.create(object_params)
end

private
    def object_params
      params.require(:post).permit(:image)
    end
```

**Comment by febero** [comment]
Removing strong params for convert_to_upload solved my problem. Thanks for your help @fsmanuel  !

**Comment by fsmanuel** [comment]
Glad it worked.
