### ISSUE TITLE
Way to test file selection?

### ISSUE THREAD

**Issue by kmiyashiro** [funkensturm/ember-cli-file-picker#24]
Is there any way to select a file (or fake it) for acceptance tests?

**Comment by fsmanuel** [comment]
@kmiyashiro There is no easy way to do that. At least I'm not aware of it.
What you can do is that you start your tests by invoking `component.filesSelected(event);`. You can provide the event with a file like that:

```js
// it is a 1x1 px black png
const file = new File(['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NkYGD4DwABCQEBtxmN7wAAAABJRU5ErkJggg=='], 'image/png');
const event = {
  target: {
    files: [file]
  }
};
component.filesSelected(event);
```

Hope this helps.

**Comment by kmiyashiro** [comment]
I see, but how do I do that in acceptance tests?

**Comment by fsmanuel** [comment]
@kmiyashiro you can try

```js
function base64toFile(b64Data, contentType, sliceSize) {
  contentType = contentType || '';
  sliceSize = sliceSize || 512;
  
  const byteCharacters = atob(b64Data);
  const byteArrays = [];
  
  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
      let slice = byteCharacters.slice(offset, offset + sliceSize);
  
      let byteNumbers = new Array(slice.length);
      for (let i = 0; i < slice.length; i++) {
          byteNumbers[i] = slice.charCodeAt(i);
      }
  
      let byteArray = new Uint8Array(byteNumbers);
  
      byteArrays.push(byteArray);
  }

  return new File(byteArrays, 'Test File', {type: contentType});;
}

const file = base64toFile('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNg+A8AAQIBANEay48AAAAASUVORK5CYII=', 'image/png');

const event = jQuery.Event('change');
event.target = {
  files: [file]
};

$('.file-picker__input').trigger(event);
```

**Comment by kmiyashiro** [comment]
:open_mouth: 

Why do I have to do the `base64toFile` if

```
const file = new File(['iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NkYGD4DwABCQEBtxmN7wAAAABJRU5ErkJggg=='], 'image/png');
```

returns a file?

**Comment by fsmanuel** [comment]
I figured that it was a broken image. Sure you can just use the file... but with the base64toFile you get a working image. It would probably be a good idea to provide the event as a helper for testing...

**Comment by kmiyashiro** [comment]
Ah, I see. I think detecting the type of file before displaying a preview would also be helpful. I'm using this for selecting CSVs so the preview just shows broken images instead of the file name/size (for example).

**Comment by fsmanuel** [comment]
Can you open a new issue for the preview of none images?

**Comment by kmiyashiro** [comment]
#25

**Comment by fsmanuel** [comment]
Thanks.

**Comment by jelhan** [comment]
Faced the same issue but run into a problem with ember run loop. @fsmanuel how did you solve? I tried with these [test helper](https://github.com/jelhan/ember-cli-file-picker-helper-demo/blob/master/tests/helpers/upload-file.js) but run into a run loop error. Have setup a [repo to demonstrate the issue](https://github.com/jelhan/ember-cli-file-picker-helper-demo/). Would appreciate any help.

**Comment by fsmanuel** [comment]
@jelhan looks like a great helper. If it works I'm happy to accept a PR.
It's a phantomjs problem you are facing. Try to replace File with Blob. There might be problems as well: http://www.finallybinary.com/blob-support-in-phantomjs/
so use [Blob.js](https://github.com/eligrey/Blob.js/) as mentioned in the post.

**Comment by fsmanuel** [comment]
@jelhan thanks a lot for your work. I'll release it with a couple of other improvements.
@kmiyashiro you can use master and use the `uploadFile` helper. See the readme.
