### ISSUE TITLE
Drag and drop still allowed with dropzone=false

### ISSUE THREAD

**Issue by timmorey** [funkensturm/ember-cli-file-picker#32]
I find that I'm still able to drag and drop a file when setting `dropzone=false`.  I assumed this option would let me disable drag-n-drop, but that doesn't seem to be the case.  Is that assumption correct, or does this parameter have another function?

If this parameter should disable drag-n-drop, I can submit a pr to hook it up..

**Comment by fsmanuel** [comment]
@timmorey I intended the option to control if a dropzone is displayed or not. But what you say makes perfect sense. It should disable the drag-n-drop behavior as well. If you have time I'm happy to accept a PR.

**Comment by fsmanuel** [comment]
@timmorey Thanks again. I'll release it with some other improvements in the pipeline.
