### ISSUE TITLE
Additional parameters in fileLoaded(s) action

### ISSUE THREAD

**Issue by thagul** [funkensturm/ember-cli-file-picker#36]
It would be useful (at least for me) to send additional parameters in `fileLoaded(s)` action. 
In the form I'm developing the user can upload two file for different scopes (for example a profile and a cover image) but if I put two different file-pickers in the form, I don't know which of the two picture the user is uploading.

I was thinking something like 

```
{{file-picker fileLoaded="fileLoaded" customValue="cover" ...}}
{{file-picker fileLoaded="fileLoaded" customValue="profile" ...}}
```

I don't know if I've missed something or this is just my need.
Thanks

**Comment by fsmanuel** [comment]
@thagul there is a similar request https://github.com/funkensturm/ember-cli-file-picker/pull/20
See my comment: https://github.com/funkensturm/ember-cli-file-picker/pull/20#issuecomment-172600640
What do you think is the best naming? Right now I prefer `meta` but I wonder if it interferes the ember internals.

**Comment by thagul** [comment]
I'm sorry, I didn't notice the PR.
For my purpose (i.e. identify the file picker) `name` would be enough; I've not preferences on naming that parameter, but, maybe, `context` fits better for the usage.

**Comment by fsmanuel** [comment]
@thagul don't worry. it's good to have an issue tracking the problem.

**Comment by jelhan** [comment]
I don't think this is the use case addressed in #20. @thagul you should just use two different actions.

**Comment by thagul** [comment]
@jelhan, you are right, I can use two different actions, it was so easy that I didn't think about it :smile: 
I suppose that with that PR, I won't need two different actions but for my needs it's not necessary.

Many thanks

**Comment by jelhan** [comment]
You would need one more complex action handling different cases. In my opinion that would be bad code style. #20 should only be for use cases where you need the target object in action.

**Comment by jelhan** [comment]
@thagul If you don't want to use different action handlers you could use action helper to pass parameters to your action handler: https://github.com/funkensturm/ember-cli-file-picker/pull/20#issuecomment-183713513

**Comment by jelhan** [comment]
@fsmanuel I think this one could also be closed.

**Comment by thagul** [comment]
Yes, I confirm it can be closed. I've resolved using different actions. I'll give a try using action helper as soon as I can.
Thanks for your help.
